### ISSUE TITLE
[REST] War Thunder Live API support

### ISSUE THREAD

**Issue by GuiRitter** [thunderstats/thunderapi#4]
**Please describe the expected behaviour, if applicable**
Access to War Thunder Live data.

**Please describe the actual behaviour, if applicable**
No access to War Thunder Live data.

**Further details**
My daily life would be so much easier if I could implement my own interface for WT Live, and I've just realized that's very close to being possible. Using Google Chrome's Dev Tools I can see the requests and the data that returns. However, apparently, they don't support cross origin requests.

If you could make work `/api/feed/get_regular/` and `/api/posts/get/`, I would be very grateful.

- Priority this issue should have – please be realistic and elaborate if possible:
Medium

**Comment by devdutchy** [comment]
I have been working on this for a while now, thanks for the WT Live endpoints, which should definitely make it easier for me to work on the WT Live endpoint. It would be nice if there is also any documentation for the `get` endpoint.

**Comment by devdutchy** [comment]
Little update: support for `/api/feed/get_regular/` and `/api/posts/get/` will be coming soon, you can use https://github.com/thunderstats/thunderapi/blob/wt_live/test/live.js to test and experiment with some features (documentation for the query parameters of the POST request used for `/api/feed/get_regular` are documentated [here](https://github.com/thunderstats/thunderapi/wiki/Endpoints-for-the-WT-Live-API)).

Just a little sidenote, I am also working on a major rewrite with major performance increases, which **will** include the new War Thunder live features, possibly alongside being able to watch a user/hashtag using an `EventEmitter`, soon™!

**Comment by GuiRitter** [comment]
Thanks, but I couldn't get that example to work, as I get the same `Failed to load https://live.warthunder.com/api/feed/get_regular/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.` message.

Searching for solutions, I found [this](https://github.com/infinitered/apisauce/issues/66). Trying it, I get `Cross-Origin Read Blocking (CORB) blocked cross-origin response https://live.warthunder.com/api/feed/get_regular/ with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.`.

I'll continue to patiently wait for the new features. Knowing they are being worked on makes me glad. Thanks again!

**Comment by devdutchy** [comment]
It looks like it works completely fine for me at least, see image:
![image](https://user-images.githubusercontent.com/26204606/41641751-9c0bde64-7466-11e8-9c69-23223bdaa17a.png)
Could you tell us under what environment you've tested the example?

**Comment by GuiRitter** [comment]
I used [Create React App](https://reactjs.org/docs/add-react-to-a-new-app.html) and pasted/modified the code in one of the lifecycle methods.

**Comment by GuiRitter** [comment]
I've seen from the screenshot that you used Node from the command line, so I did the same and, sure enough, that code worked! If I manage to integrate it with my React app (and I think I will), then I'm set. Thanks!

**Comment by devdutchy** [comment]
I've pushed the other changes form #5 to master including the example code on using the WT Live API using POST requests, considering it looks like you're set I've closed this alongside #5 as well.
I will continue working on integrating War Thunder Live API support in the `wt_live` branch so feel free to use that branch as soon as the first commits are pushed!
